### ISSUE TITLE
A registered user can add the same recipe multiple times to a recipe list

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-ChristianBlom84#2] opened 2019-03-22 10:36 UTC
Results in:
![image](https://user-images.githubusercontent.com/343422/54817172-8b74be00-4c96-11e9-8a26-d900fdbeeec4.png)

Response (when adding second time):
![image](https://user-images.githubusercontent.com/343422/54817215-a5160580-4c96-11e9-8fea-3cec80fe84c6.png)

**Comment by axeberg** [comment] 2019-03-22 10:36
Technically more of a backend issue…

**Comment by ChristianBlom84** [comment] 2019-03-22 10:56
Believe it or not - I actually left this in on purpose as a feature. I figured someone might want to add a recipe as perhaps both an appetizer and a dessert, or something like that. Maybe too much user freedom?

**Comment by ChristianBlom84** [comment] 2019-03-23 13:53
Closing, working as intended. Feel free to reopen if you still want me to fix it.

**Closed as completed by ChristianBlom84** 2019-03-23 13:53 UTC
Labels: komplettera
